<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Kebijakan Privasi_a-dy056i2b1cq8</name>
   <tag></tag>
   <elementGuidId>ca74b645-e1d6-4781-88fe-c6125aaa795a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-dy056i2b1cq8&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-dy056i2b1cq8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-dy056i2b1cq8&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4bc9f113-2c95-4719-9234-20620d6c0831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>0b08a9dd-617a-480a-bc0b-45cecc4de3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>2a8d8602-4e0a-4d98-8ac3-1bc8692fe2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>f3b6748d-ec08-495a-88e0-987e247596cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f7460d6d-475a-4b09-ab5b-1449a0f30719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-dy056i2b1cq8</value>
      <webElementGuid>a9bf5ba5-827a-4d3b-9ed5-8e3f2e6d9ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75f3a870-3ee0-4322-8976-3338e381c51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2cde0c90-9fc1-4695-99bb-2527e463b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>d15a7d5f-e250-467b-b21b-316e96d3b166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lco17kUAAAAAKFNCdXJK61Kc_Vy3VC8iP_uM_xu&amp;co=aHR0cHM6Ly93d3cuY2VybWF0aS5jb206NDQz&amp;hl=id&amp;type=image&amp;v=EGbODne6buzpTnWrrBprcfAY&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=92bpdj6n91ds</value>
      <webElementGuid>f91143a7-be2c-4495-a873-79b53ff1da2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/div[@class=&quot;superapp-container content&quot;]/div[@class=&quot;container_Eq-qi&quot;]/div[@class=&quot;w-100 d-flex m-t-16&quot;]/div[1]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>b116aa72-1470-48d2-b588-bae9a4937926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-dy056i2b1cq8']</value>
      <webElementGuid>76dd9a49-fe17-4048-a2f9-584750ae7179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div/div[5]/div/div/div/div/div/iframe</value>
      <webElementGuid>27117aff-4c0e-4d7e-a12d-99b6c3aac379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>102aa988-3509-4a6b-8f4e-c4863d9ff94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-dy056i2b1cq8' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lco17kUAAAAAKFNCdXJK61Kc_Vy3VC8iP_uM_xu&amp;co=aHR0cHM6Ly93d3cuY2VybWF0aS5jb206NDQz&amp;hl=id&amp;type=image&amp;v=EGbODne6buzpTnWrrBprcfAY&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=92bpdj6n91ds']</value>
      <webElementGuid>691d138b-57b5-4c92-ae31-926c0e83bc9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
